# Generated by Django 5.2.8 on 2025-11-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spacepermission",
            name="can_ask",
        ),
        migrations.RemoveField(
            model_name="spacepermission",
            name="can_view",
        ),
        migrations.AddField(
            model_name="spacepermission",
            name="role",
            field=models.CharField(
                choices=[("owner", "Owner"), ("member", "Member")],
                default="member",
                max_length=20,
            ),
        ),
    ]
