# Generated by Django 5.2.8 on 2025-11-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
