"""
Django settings for graphrag_marketplace project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-6d5yio-gf7v6u^bnnpcd_k6$%+_$-f_qzl3(9d98v@)s)jl01(')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "whitenoise.runserver_nostatic", # Use whitenoise for static files in dev too
    # Local
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", # Whitenoise
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.ForcePasswordChangeMiddleware",  # Force password change middleware
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "graphrag_marketplace.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"], # Add templates dir
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.marketplace_context",
            ],
        },
    },
]

WSGI_APPLICATION = "graphrag_marketplace.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Media Files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Marketplace Configuration
MARKETPLACE_TITLE = "GraphRAG Marketplace"

# Login/Logout
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "marketplace"

# LDAP Configuration (Placeholder - Uncomment and configure for prod)
# import ldap
# from django_auth_ldap.config import LDAPSearch, GroupOfNamesType

# AUTH_LDAP_SERVER_URI = "ldap://ldap.example.com"
# AUTH_LDAP_BIND_DN = ""
# AUTH_LDAP_BIND_PASSWORD = ""
# AUTH_LDAP_USER_SEARCH = LDAPSearch("ou=users,dc=example,dc=com",
#     ldap.SCOPE_SUBTREE, "(uid=%(user)s)")

# AUTHENTICATION_BACKENDS = (
#     "django_auth_ldap.backend.LDAPBackend",
#     "django.contrib.auth.backends.ModelBackend",
# )

# GraphRAG Configuration
GRAPHRAG_CONFIG = {
    # LLM Settings
    "LLM_MODEL_NAME": os.environ.get("LLM_MODEL_NAME", "gpt-3.5-turbo"),
    "OPENAI_API_KEY": os.environ.get("OPENAI_API_KEY"),
    "OPENAI_API_BASE": os.environ.get("OPENAI_API_BASE"),
    "LLM_MODEL_PATH": os.environ.get("LLM_MODEL_PATH", "models/Qwen2.5-7B-Instruct-Q4_K_M.gguf"),
    "LLM_GPU_LAYERS": int(os.environ.get("LLM_GPU_LAYERS", 0)),
    "LLM_CONTEXT_SIZE": int(os.environ.get("LLM_CONTEXT_SIZE", 8192)), # Default to 8192 for safety
    "LLM_HF_REPO_ID": os.environ.get("LLM_HF_REPO_ID", "bartowski/Qwen2.5-7B-Instruct-GGUF"),
    "LLM_HF_FILENAME": os.environ.get("LLM_HF_FILENAME", "Qwen2.5-7B-Instruct-Q4_K_M.gguf"),
    
    # Embedding Settings
    "EMBEDDING_MODEL_NAME": os.environ.get("EMBEDDING_MODEL_NAME", "sentence-transformers/all-MiniLM-L6-v2"),
    "EMBEDDING_CACHE_FOLDER": os.environ.get("EMBEDDING_CACHE_FOLDER", None),
    
    # Document Chunking Settings
    "CHUNK_SIZE": int(os.environ.get("CHUNK_SIZE", 500)),  # Characters per chunk
    "CHUNK_OVERLAP": int(os.environ.get("CHUNK_OVERLAP", 50)),  # Overlap between chunks
}
